/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as TrackRouteImport } from './routes/track'
import { Route as IndexRouteImport } from './routes/index'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/track': typeof TrackRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/track': typeof TrackRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/track': typeof TrackRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/track' | '/vision-mission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/track' | '/vision-mission'
  id: '__root__' | '/' | '/track' | '/vision-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrackRoute: typeof TrackRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrackRoute: TrackRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
